version: '3.8'
services:
  app:
    container_name: User_Service
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 5003:5003
    environment:
      - MONGO_KEY=${MONGO_KEY}
      - JWT_SECRET = ${JWT_SECRET}
